libvirt_dns_server: 172.16.115.254
libvirt_dns_zone: dell115.u13.org
libvirt_ip_prefix: '172.16.115'

libvirt_vms:
  00.webserver:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.60"

  01.webserver:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.61"

  00.mysql:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.70"

  01.mysql:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.71"
