---
# tasks file for common

- name: Stop apache2
  service:
    state: stopped
    name: apache2


- name: Install common apt-packages
  apt:
  name: common
  state: present
  with_items:
    - htop
    - nload
    - telnet
    - netstat
    - ntp
    - git

- name: Set timezone
  timezone:
    name: Europe/Paris

- name: Create app user
  group:
    name: app-user
  user:
    name: app-user
    append: yes
    comment: "user app"
    uid: 1040
    group: app-user
