---
# tasks file for mysql

- name: Install mysql packages
  apt:
    name: mysql
    state: present
    with_items:
      - mysql
      - mysql-client
      - mysql-server

- name: start mysql
  service:
    name: mysql
    state: started
    enabled: true
