- name: Setup Mysql database and utilities
  apt:
    state: present
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - mysql-server
    - libdbd-mysql
    - mysql-client
    - python-mysqldb # Required by the Ansible

- name: Make sure Mysql binds to all interfaces
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    owner: root
    group: root
    mode: 0644
  register: __mysql_configuration

- name: Make sure Mysql is started and enabled at boot time
  service:
    name: mysql
    state: "{{ (__mysql_configuration | changed) | ternary('restarted', 'started') }}"
    enabled: yes
    
- name: Set a password for the MySql root user
  mysql_user:
    state: present
    name: root
    password: "{{ mysql_server_root_pwd }}"

- name: Drop the ~/.my.cnf
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'

# Drop anonymous users
- name: Drop all anonymous user accounts
  mysql_user:
    state: absent
    name: ''
    host_all: yes