---
# tasks file for mysql

- name: Install mysql packages
  apt:
  name: mysql
  state: present
  with_items:
    - mysql
    - mysql-client
    - mysql-server

- name: Mot de passe root
  mysql_user:
    name: root
    password: root
    state: present
