---
# tasks file for mysql

# cryptage ansible-vault

- name: Install mysql packages
  apt:
  name: "{{ item }}"
  state: present
  with_items:
    - mysql
    - mysql-client
    - mysql-server
    - MySQL-python
    - python-pip
    - python-dev
    - libdbd-mysql

- name: Install python mysql
  apt:
    name: python-mysqldb
    state: latest

- name: Launch MySQL service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Tune MySQL configuration
  template:
    src: ./resources/my.cnf
    dest: /etc/my.cnf
    mode: 0644
  notify:
    - restart mysqld

- name: Create the Drupal database
  mysql_db:
    db: "{{ db_name }}"
    state: present

- name: Create the user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"

- name: Mot de passe root
  mysql_user:
    login_user: root
    login_password: root
    name: sql-user
    state: present
