---
# tasks file for mysql

# cryptage ansible-vault

- name: Install mysql packages
  apt:
  name: mysql
  state: present
  with_items:
    - mysql
    - mysql-client
    - mysql-server
    - MySQL-python
    - python-pip
    - python-dev
    - libdbd-mysql

- name: Install python mysql
  apt: name=python-mysqldb state=latest

- name: Create the Drupal database
  mysql_db: db={{ db_name }} state=present

- name: Create the user
  mysql_user:
  name: {{ db_user }}
  password: {{ db_password }}
  host: localhost

- name: Mot de passe root
  mysql_user:
    login_user: root
    login_password: root
    name: sql-user
    state: present
