---
# tasks file for mysql

# cryptage ansible-vault

- name: Install mysql packages
  apt:
  name: packet mysql
  state: present
  with_items:
    - mysql
    - mysql-client
    - mysql-server
    - MySQL-python
    - python-pip
    - python-dev
    - libdbd-mysql

- name: Install python mysql
  apt:
    name: python-mysqldb
    state: latest

- name: Create a new database with name 'bobdata'
  mysql_db:
    name: bobdata
    state: present

- name: Create the user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"

- name: Mot de passe root
  mysql_user:
    login_user: root
    login_password: root
    name: sql-user
    state: present
