---
# tasks file for mysql

- name: Install mysql packages
  apt:
  name: mysql
  state: present
  with_items:
    - mysql
    - python-mysqldb
    - mysql-client
    - mysql-server
    - MySQL-python
    - python-pip
    - python-dev

- name: Mot de passe root
  mysql_user:
    name: root
    password: root
    priv: '*.*:ALL'
    state: present
