---
# tasks file for mysql

- name: Install mysql packages
  apt:
  name: mysql
  state: present
  with_items:
    - mysql
    - python-mysqldb
    - mysql-client
    - mysql-server
    - MySQL-python
    - python-pip
    - python-dev

- name: Install the MySQL-python through pip
  sudo: yes
  pip:
    name: mysql
    state: forcereinstall
  with_items:
    - pip
    - MySQL-python

- name: Mot de passe root
  mysql_user:
    name: root
    password: root
    priv: '*.*:ALL'
    state: present
