---
# tasks file for mysql

- name: Install mysql packages
  apt:
  name: mysql
  state: present
  with_items:
    - mysql
    - mysql-client
    - mysql-server

- name: install python mysql bindings
  apt:
  name: python-mysqldb
  state: installed
  become: yes
  become_method: sudo

- name: Mot de passe root
  mysql_user:
    name: root
    password: root
    priv: '*.*:ALL'
    state: present
