################################################################################
# > Playbook used to configure databases
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure databases
  hosts: all
  become: yes

  roles:
    - common
    - mysql
    - webapp-database